var question;

var questionList = [
    "THINGS... it would be hard to do in space.",
    "THINGS... you don't understand about sex.",
    "THINGS... you would love to have an audience for.",
    "THINGS... you like about penises.",
    "THINGS... that will kill you.",
    "THINGS... you'd like to use for target practice.",
    "THINGS... you use the word \"fuck\" for.",
    "THINGS... you would like to include in your sex dungeon.",
    "THINGS... you wish you didn't know about your mother.",
    "THINGS... you enjoy eating after sex.",
    "THINGS... you like in a woman.",
    "THINGS... your partner finds exciting.",
    "THINGS... you shouldn't tease.",
    "THINGS... you would like about being a celebrity.",
    "THINGS... you hope your parents never find out.",
    "THINGS... you never want to find in your underwear.",
    "THINGS... women hate during oral sex.",
    "THINGS... you are afraid of.",
    "THINGS... that are more trouble than they are worth.",
    "THINGS... you wouldn't want to be famous for.",
    "THINGS... you dream about doind with ____. (reader adds name)",
    "THINGS... that sound dirty.",
    "THINGS... that make you cringe.",
    "THINGS... you can't change.",
    "THINGS... you cannot do while also having sex.",
    "THINGS... women will never understand.",
    "THINGS... that are better than sex.",
    "THINGS... you were not expecting.",
    "THINGS... you would say to describe a vagina.",
    "THINGS... you learned from watching porn.",
    "THINGS... God screwed up.",
    "THINGS... that would make your life complete.",
    "THINGS... you say when you want him to hurry up and climax.",
    "THINGS... women totally lie about.",
    "THINGS... that would make a badass biker cry.",
    "THINGS... you wish were over.",
    "THINGS... other than sex, that give you an orgasm.",
    "THINGS... that get you excited.",
    "THINGS... you refer to as \"medicine\" but your doctor does not.",
    "THINGS... you don't like to touch.",
    "THINGS... that make a woman scream \"YES!\"",
    "THINGS... that make a penis better than a vagina.",
    "THINGS... you would like to have control over.",
    "THINGS... that are the worst sins you can thinnk of.",
    "THINGS... you like about vaginas.",
    "THINGS... you often prefer to sex.",
    "THINGS... you would like to run over with a car.",
    "THINGS... that are evil.",
    "THINGS... Superman does with his powers when no one is looking.",
    "THINGS... that are messy.",
    "THINGS... you are jelous of.",
    "THINGS... that you have an insatiable desire for.",
    "THINGS... that are good about dating a cougar.",
    "THINGS... that make a girlfriend perfect.",
    "THINGS... you would title an X-rated version of a Disney film.",
    "THINGS... you do when no one else is home.",
    "THINGS... that make you feel good.",
    "THINGS... you have never liked.",
    "THINGS... you forgot to tell your partner.",
    "THINGS... women do not like to do while menstruating.",
    "THINGS... you shouldn't screw around with.",
    "THINGS... you DO NOT want anyone to find in your bedroom if you die.",
    "THINGS... you would like to forget.",
    "THINGS... that will result in divorce.",
    "THINGS... about aliens that might be fun.",
    "THINGS... you might like about being in prison.",
    "THINGS... that piss you off.",
    "THINGS... that could be used as a dildo in a pinch.",
    "THINGS... that make a vagina better than a penis.",
    "THINGS... that make you feel better.",
    "THINGS... you call your favorite sex toy.",
    "THINGS... that are only solved by getting really high.",
    "THINGS... you are glad are not your problem.",
    "THINGS... that can ruin a porn movie.",
    "THINGS... you wish someone had told you about sex.",
    "THINGS... people call breasts.",
    "THINGS... you would sell your soul for.",
    "THINGS... that are awesome about lesbians.",
    "THINGS... that will get you called a pussy.",
    "THINGS... that are on your shit list.",
    "THINGS... you just heard about for the first time.",
    "THINGS... the First Lady won't let the President do.",
    "THINGS... that really got Adam and Eve kicked out of Eden.",
    "THINGS... that prove you're a horrible, aweful person.",
    "THINGS... you shouldn't even ask a friend to do.",
    "THINGS... you hate about politics.",
    "THINGS... you shouldn't get as a tattoo.",
    "THINGS... people often call a vagina other than a vagina.",
    "THINGS... you fantasize about.",
    "THINGS... you wouldn't miss.",
    "THINGS... only the president can get away with.",
    "THINGS... that are so good you don't want to share with anyone.",
    "THINGS... a prostitute has never heard of before.",
    "THINGS... you wish were free.",
    "THINGS... that should be much bigger.",
    "THINGS... you are sorry you missed.",
    "THINGS... that make you cry.",
    "THINGS... that get your grandmother all hot and bothered.",
    "THINGS... Captain Hook needs to be extra careful about.",
    "THINGS... you would title an X-rated version of a TV sitcom.",
    "THINGS... you will do for someone else if they do it for you.",
    "THINGS... you shouldn't have said.",
    "THINGS... the president thinks about while masturbating.",
    "THINGS... your own TV show would be about.",
    "THINGS... you shouldn't do with your eyes closed.",
    "THINGS... that are a drag.",
    "THINGS... you can think but you shouldn't say aloud.",
    "THINGS... men will never understand.",
    "THINGS... that are going to hurt.",
    "THINGS... you are nervous about having behind.",
    "THINGS... that would make church a helluva lot more fun.",
    "THINGS... you keep locked up.",
    "THINGS... your parents forgot to teach you about life.",
    "THINGS... really old people smell like.",
    "THINGS... you can trade cigarettes for in jail.",
    "THINGS... you never expected to find in your mother's bedside drawer.",
    "THINGS... you would like about the rock 'n roll lifestyle.",
    "THINGS... women can hide in their bras.",
    "THINGS... that look better than they taste.",
    "THINGS... God is pissed at you for.",
    "THINGS... that mean your relationship is definitely over.",
    "THINGS... you have never told anyone.",
    "THINGS... you shouldn't blame on someone else.",
    "THINGS... that should never have gone on as long as they did.",
    "THINGS... you would like to try over again.",
    "THINGS... you like in a man.",
    "THINGS... that get women excited.",
    "THINGS... you don't want to find in you vomit.",
    "THINGS... you would like to try.",
    "THINGS... you wish you could get away with.",
    "THINGS... it's fun to do with more than two people.",
    "THINGS... that will never change.",
    "THINGS... you don't care about.",
    "THINGS... that are frustrating.",
    "THINGS... you shouldn't do on your honeymoon.",
    "THINGS... you are proud of.",
    "THINGS... that are hard.",
    "THINGS... you wish you were allowed to do naked.",
    "THINGS... you did not expect to hear from your boss... especially at work.",
    "THINGS... you should keep your genitals away from.",
    "THINGS... that your farts smell better than.",
    "THINGS... that turn you off.",
    "THINGS... to remember when dumbing a dead body.",
    "THINGS... you never wanna find in your poop.",
    "THINGS... that would be horrible ways to die.",
    "THINGS... that were never really explained properly.",
    "THINGS... you cannot take seriously.",
    "THINGS... that women will do that men won't.",
    "THINGS... you would say to your evil boss before the words \"I quit.\"",
    "THINGS... you shouldn't do in the dark.",
    "THINGS... your government isn't telling you.",
    "THINGS... you didn't expect to hear from your parents.",
    "THINGS... that confirm you are gay.",
    "THINGS... that never fail to liven up a party.",
    "THINGS... you know more about than anyone else.",
    "THINGS... that give you nightmares.",
    "THINGS... that are always getting bettter.",
    "THINGS... you wouldn't think to make a bong of.",
    "THINGS... you should never do on a first date.",
    "THINGS... you have never tried.",
    "THINGS... you shouldn't rely on your parents for.",
    "THINGS... men think about while having sex.",
    "THINGS... people are paid too much money for.",
    "THINGS... you shouldn't use as a sex toy.",
    "THINGS... you say to a one night stand when they catch you sneaking out.",
    "THINGS... you shouldn't do in your pajamas.",
    "THINGS... you know more about than your parents did at your age.",
    "THINGS... you dream about.",
    "THINGS... that are complicated.",
    "THINGS... you think about during sex.",
    "THINGS... that are good about dating an older man.",
    "THINGS... you've changed your mind about.",
    "THINGS... you would like to add to your sex life.",
    "THINGS... Harry Potter should have been using his magic for.",
    "THINGS... that scare the hell out of you.",
    "THINGS... you're ashamed about googling.",
    "THINGS... you are attracted to.",
    "THINGS... Disney decided would not make a good animated film.",
    "THINGS... that are your favorite curse words.",
    "THINGS... you are still not sure you understand.",
    "THINGS... even the Pope can't get away with.",
    "THINGS... that would describe your love life.",
    "THINGS... your own personal robot would do.",
    "THINGS... that turn you on.",
    "THINGS... people have a hard time saying.",
    "THINGS... doctors have removed from patients' butts.",
    "THINGS... Snow White nicknamed her favorite dwarf.",
    "THINGS... you really screwed up.",
    "THINGS... you don't like about humans.",
    "THINGS... that give you wet dreams.",
    "THINGS... most people think is inappropriate but you are actually okay with.",
    "THINGS... that give Batman a boner.",
    "THINGS... you like about boobs.",
    "THINGS... women think about while having sex.",
    "THINGS... that freak you out.",
    "THINGS... you shouldn't whip out without a warning.",
    "THINGS... no one should EVER admit to fantasizing about.",
    "THINGS... that jurt when you up in the morning.",
    "THINGS... you cannot stop doing no matter how hard you try.",
    "THINGS... people do without thinking.",
    "THINGS... that would embarrass Howard Stern.",
    "THINGS... you would say to describe a penis.",
    "THINGS... you have always wanted to do.",
    "THINGS... you enjoy doing after sex.",
    "THINGS... you won't do on a first date.",
    "THINGS... your ex never gave back after you broke up.",
    "THINGS... you would add to the 10 commandments.",
    "THINGS... you wish came out of nipples.",
    "THINGS... you notice that tell you a chick is a sure thing.",
    "THINGS... you can say to get out of having sex.",
    "THINGS... that men will do that women won't.",
    "THINGS... you can use when your vibrator is out of batteries.",
    "THINGS... that are missing from your life.",
    "THINGS... you could never give up.",
    "THINGS... you like to touch with your hands.",
    "THINGS... you have never told anyone about your family.",
    "THINGS... you would say to describe a penis.",
    "THINGS... that could put you off sex for a while.",
    "THINGS... you would rather die than do.",
    "THINGS... cannibals serve for dessert.",
    "THINGS... that may cause the end of the world as we know it.",
    "THINGS... you wouldn't do for a million dollars.",
    "THINGS... you wish you could do in your pajamas.",
    "THINGS... women do to piss off other women.",
    "THINGS... that could kill you.",
    "THINGS... that drive you crazy about your family.",
    "THINGS... a proctologist nicknames his finger.",
    "THINGS... people often call a penis other than a penis.",
    "THINGS... men lie about.",
    "THINGS... you shouldn't just spring on your partner in the bedroom.",
    "THINGS... that will get you sent to hell.",
    "THINGS... that make you pee your pants.",
    "THINGS... in your kitchen that could give you an orgasm.",
    "THINGS... that burn.",
    "THINGS... hair should not grow on.",
    "THINGS... that men do totally differently than women.",
    "THINGS... that make a boyfriend perfect.",
    "THINGS... you shouldn't say while having sex.",
    "THINGS... that will ALWAYS get you laid.",
    "THINGS... that are accomplished easier with alcohol.",
    "THINGS... that smell funny but you eat them anyway.",
    "THINGS... people say instead of \"sexual intercourse.\"",
    "THINGS... you would like to blow up.",
    "THINGS... you wouldn't want to be underneath.",
    "THINGS... you hate to get in your hair.",
    "THINGS... that are kinky.",
    "THINGS... you don't like the sound of.",
    "THINGS... you wish you didn't know about your father.",
    "THINGS... you have never seen advertised.",
    "THINGS... your ex is going to miss.",
    "THINGS... you can't take your eyes off of.",
    "THINGS... that shouldn't be mounted.",
    "THINGS... zombies do when they're not eating people.",
    "THINGS... you learned from the Boy Scouts.",
    "THINGS... you would like to change the rules to.",
];

function getQuestion() {
    question = questionList[Math.floor(Math.random() * questionList.length)];
    document.getElementById("q-card-text").innerHTML = question;
}

$("#question-card #q-card-text").hide();
$(".next-button").hide();

$("#question-card").append("<button class='start-button' onclick='getQuestion()'>Click to Start</button>");

$(".start-button").click(function () {
    $("#question-card #q-card-text").show();
    $(this).hide();
    $(".next-button").show();
});
