var bCards = [
"____ kid - tested mother - approved.",
"____ : good to the last drop.",
"____ ? There's an app for that.",
"____ . Betcha can't have just one.",
"____ . High five bro.",
"____ . It's a trap!",
"____ . That's how I want to die.",
"A romantic candlelit dinner would be incomplete without ____ .",
"After blacking out during New Year's Eve, I was awoken by ____ .",
"After months of debate, the Occupy Wall Street General Assembly could only agree on 'More ____ !'",
"After the earthquake, Sean Penn bought ____ to the people of Haiti.",
"Alternative medicine is now embracing the curative powers of ____ .",
"And I would have gotten away with it, too, if it hadn't been for ____ .",
"Anthropologists have recently discovered a primitive tribe that worships ____ .",
"Before I run for president, I must destroy all evidence of my involvement with ____ .",
"BILLY MAYS HERE FOR ____ .",
"But before I kill you, Mr. Bond, I must show you ____ .",
"Charades was ruined for me forever when my mom had to act out ____ .",
"Coming to Broadway this season, ____ : The Musical.",
"Dear Abby, I'm having some trouble with ____ and would like your advice.",
"During his midlife crisis, my dad got really into ____ .",
"During Picasso's often - overlooked Brown Period, he produced hundreds of paintings of ____ .",
"During sex, I like to think about ____ .",
"Every Christmas my uncle gets drunk and tells the story about ____ .",
"Everyone down on the ground! We don't want to hurt anyone. We're just here for ____ .",
"He who controls ____ controls the world.",
"How am I maintaining my relationship status.",
"I do not know with what weapons World War III will be fought, but World War IV will be fought with.",
"I drink to forget ____ .",
"I got 99 problems but ____ ain't one.",
"I learned the hard way that you can't cheer up a grieving friend with ____ .",
"I'm sorry professor, but I couldn't complete my homework because of ____ .",
"In 1,000 years when paper money is but a distant memory, ____ will be our currency.",
"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ____ .",
"In his new self - produced album, Kanye West raps over the sounds of ____ .",
"In his newest and most difficult stunt, David Blaine must escape from ____ .",
"In its new tourism campaign, Detroit proclaims that it has finally eliminated ____ .",
"In L.A. county Jail, word is you can trade 200 cigarettes for ____ .",
"In Michael Jackson's final moments, he thought about ____ .",
"In Rome, there are whisperings that the Vatican has a secret room devoted to ____ .",
"In the distant future, historians will agree that ____ marked the beginning of America's decline.",
"In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.",
"Instead of coal, Santa now gives the bad children ____ .",
"It's a pity that kids these days are all getting involved with ____ .",
"Jesus is ____ .",
"Life for American Indians was forever changed when the White Man introduced them to ____ .",
"Little Miss Muffet, Sat on a tuffet, Eating her curds and ____ .",
"Major League Baseball has banned ____ for giving players an unfair advantage.",
"Maybe she's born with it. Maybe it's ____ .",
"Members of New York's social elite are paying thousands of dollars just to experience ____ .",
"MTV's new reality show features eight washed - up celebrities living with ____ .",
"My country, 'tis of thee, sweet land of ____ .",
"My new favorite porn star is Joey \" ____ \" McGee.",
"Next from J.K. Rowling: Harry Potter and the Chamber of ____ .",
"Next on ESPN2: The World Series of ____ .",
"Next time on Dr. Phil: How to talk to your child about ____ .",
"On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and ____ .",
"Only two things in life are certain: death and ____ .",
"Science will never explain the origin of ____ .",
"Studies show that lab rats navigate mazes 50% faster after being exposed to ____",
"The CIA now interrogates enemy agents by repeatedly subjecting them to ____ .",
"The class field trip was completely ruined by ____ .",
"The Five Stages of Grief: denial, anger, bargaining, ____ , and acceptance.",
"The healing process began when I joined a support group for victims of ____ .",
"The socialist governments of Scandanavia have declared that access to ____ is a basic human right.",
"The votes are in, and the new high school mascot is ____ .",
"This holiday season, Tim Allen must overcome his fear of ____ to save Christmas.",
"This is the way the world ends This is the way the world ends Not with a bang but with ____ .",
"This is your captain speaking. Fasten your seatbelts and prepare for ____ .",
"This month's Cosmo: \"Spice up your sex life by bringing ____ into the bedroom.\"",
"This reason on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ____ and his wits.",
"Tonight on 20/20: What you don't know about ____ could kill you.",
"TSA guidelines now prohibit ____ on airplanes.",
"Wake up, America. Christmas is under attack by secular liberals and their ____ .",
"War! What is it good for?",
"What am I giving up for Lent?",
"What are my parents hiding from me?",
"What brought the orgy to a grinding halt?",
"What did I bring back from Mexico?",
"What did the US airdrop to the children of Afghanistan?",
"What did Vin Diesel eat for dinner?",
"What do old people smell like?",
"What does Dick Cheney prefer?",
"What don't you want to find in your Chinese food?",
"What ended my last relationship?",
"What gets better with age?",
"What gives me uncontrollable gas?",
"What has been making life difficult at the nudist colony?",
"What helps Obama unwind?",
"What is Batman's guilty pleasure?",
"What keeps me warm during the cold, cold winter?",
"What never fails to liven up the party?",
"What do people like.",
"What will always get you laid?",
"What will I bring back in time to convince people that I am a powerful wizard?",
"What would grandma find disturbing, yet oddly charming?",
"What's a girl's best friend?",
"What's my anti - drug?",
"What's my secret power?",
"What's Teach for America using to inspire inner city students to succeed?",
"What's that smell?",
"What's that sound?",
"What's the crustiest?",
"What's the gift that keeps on giving?",
"What's the most emo?",
"What's the new fad diet?",
"What's the next Happy Meal toy?",
"What's there a ton of in heaven?",
"When all else fails, I can always masturbate to ____ .",
"When I am a billionaire, I shall erect a 50 - foot statue to commemorate ____ .",
"When I am President of the United States, I will create the Department of ____ .",
"When I pooped, what came out of my butt?",
"When Pharaoh remained unmoved, Moses called down a Plague of ____ .",
"When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ____ .",
"Why am I sticky?",
"Why can't I sleep at night?",
"Why do I hurt all over?",
"In the seventh circle of Hell, sinners must endure ____ for all eternity.",
"A successful job interview begins with a firm handshake and ends with ____ .",
"Lovin' you is easy ’cause you’re ____ .",
"The blind date was going horribly until we discovered our shared interest in ____ .",
"____ . Awesome in theory, kind of a mess in practice.",
"I'm not like the rest of you. I’m too rich and busy for ____ .",
"What left this stain on my couch?",
"Call the law offices of Goldstein & Goldstein, because no one should have to tolerate ____ in the workplace.",
"Turns out that ____ Man was neither the hero we needed nor wanted.",
"As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ____ .",
"Money can't buy me love, but it can buy me ____ .",
"And what did you bring for show and tell?",
"During high school I never really fit in until I found ____ club.",
"Hey baby, come back to my place and I'll show you ____ .",
"To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ____ .",
"Finally! A service that delivers ____ right to your door.",
"My gym teacher got fired for adding ____ to the obstacle course.",
"<p>(Draw 2, Pick 3)</p> ____ + ____ = ____",
"<p>(Draw 2, Pick 3)</p> I went from ____ to ____ , all thanks to.",
"<p>(Draw 2, Pick 3)</p> Make a haiku.",
"<p>(Pick 2)</p> ____ would be woefully incomplete without ____ .",
"<p>(Pick 2)</p> ____ is a slippery slope that leads to ____ .",
"<p>(Pick 2)</p> An international tribunal has found ____ guilty of ____ .",
"<p>(Pick 2)</p> And the Academy Award for ____ goes to ____ .",
"<p>(Pick 2)</p> Before ____ , all we had was ____ .",
"<p>(Pick 2)</p> Dear Sir or Madam, We regret to inform you that the office of ____ has denied your request for ____ .",
"<p>(Pick 2)</p> For my next trick, I will pull ____ out of ____ .",
"<p>(Pick 2)</p> I never truly understood ____ until I encountered ____ .",
"<p>(Pick 2)</p> I spent my whole life working toward ____ , only to have it ruined by ____ .",
"<p>(Pick 2)</p> If God didn't want us to enjoy ____ , he wouldn't have given us ____ .",
"<p>(Pick 2)</p> In a pinch, ____ can be a suitable substitute for ____ .",
"<p>(Pick 2)</p> In a world ravaged by ____ , our only solace is ____ .",
"<p>(Pick 2)</p> In M. Night Shamalan's new movie, Bruce Willis discovers that ____ had really been ____ all along.",
"<p>(Pick 2)</p> Lifetime presents ____ , the story of ____ .",
"<p>(Pick 2)</p> Michael Bay's new three - hour action epic pits ____ against ____ .",
"<p>(Pick 2)</p> Rumor has it that Vladimir Putin's favorite dish is ____ stuffed with ____ .",
"<p>(Pick 2)</p> Step 1: ____ Step 2 ____ Step 3: Profit.",
"<p>(Pick 2)</p> That's right I killed ____ . How you ask? ____ .",
"<p>(Pick 2)</p> What's the next superhero/sidekick duo?",
"<p>(Pick 2)</p> When I was tripping on acid ____ turned into ____ .",
"<p>(Pick 2)</p> You haven't truly lived until you've experienced ____ and ____ at the same time.",
"<p>(Pick 2)</p> My mom freaked out when she looked at my browser history and found ____ .com/ ____ .",
"<p>(Pick 2)</p> My life is ruled by a vicious cycle of ____ and ____ .",
"<p>(Pick 2)</p> ____ : Hours of fun. Easy to use. Perfect for ____ !",
"<p>(Pick 2)</p> When you get right down to it, ____ is just ____ .",
"<p>(Pick 2)</p> With enough time and pressure, ____ will turn into ____ .",
"<p>(Pick 2)</p> After months of practice with ____ , I think I'm finally ready for ____ .",
"As part of his contract, Prince won't perform without ____ in his dressing room.",
"<p>(Pick 2)</p> Having problems with ____ ? Try ____ !",
"<p>(Pick 2)</p> Listen, son. If you want to get involved with ____ , I won't stop you. Just steer clear of ____ .",];

function randomBlackCard(){
var blackCard = bCards[Math.floor(Math.random()*bCards.length)];
return blackCard;
}
document.getElementById("b-card-text").innerHTML = randomBlackCard();
